openapi: 3.1.0
info:
  title: Template Swagger API Documentation
  description: |-
    API documentation for the template projects, created by GDSC-DUT. This documentation offers detailed insights into the common API endpoints used across all templates.
  contact:
    email: contact@gdsc.dev
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
tags:
  - name: authentication
    description: Operations about authentication
  - name: users
    description: Operations about user
  - name: admin
    description: Operations about admin
paths:
  /auth/login:
    post:
      tags:
        - authentication
      operationId: login
      requestBody:
        description: default email and password, seeded in the database
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@gmail.com
                password:
                  type: string
                  example: password123
              required:
                - email
                - password
      responses:
        "200":
          description: The user is authenticated, and an access token is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                required:
                  - access_token
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  value:
                    error_code: 104
                    message: Invalid syntax
                    details:
                      [
                        The email field is required,
                        The password field is required,
                      ]
        "401":
          description: "Return this response if one of the following error occurs: 102"
          content:
            application/json:
              examples:
                error_102_example:
                  $ref: "#/components/examples/error_102_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
  /auth/register:
    post:
      tags:
        - authentication
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  example: Pham Tien
                  description: |-
                    ^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$
                    (Starts with one or more letters,
                    allows for characters like spaces,
                    hyphens, apostrophes, commas,
                    and periods within the name,
                    and does not allow trailing spaces)
                email:
                  type: string
                  example: user@gmail.com
                  description: |-
                    ^.*@.*\.(com|net|org)$
                    (The email address must contain at least one character before and after the '@' symbol,
                    and end with an extension like .com, .net, .org.)
                password:
                  type: string
                  example: Password123
                  description: |-
                    ^.*(?=.{7,50})(?=.*\d)(?=.*[A-Z]).*$
                    (The length of the string must be between 7 and 50 characters.
                    It must contain at least one digit.
                    It must contain at least one uppercase letter)
                confirm_password:
                  type: string
                  example: Password123
              required:
                - full_name
                - email
                - password
                - confirm_password
      responses:
        "201":
          description: User registered successfully. Email and full_name are returned.
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    example: 1
                  full_name:
                    type: string
                    example: Pham Tien
                  email:
                    type: string
                    example: user@gmail.com
                required:
                  - id
                  - full_name
                  - email
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  value:
                    error_code: 104
                    message: Invalid syntax
                    details: [
                        "Missing required email field",
                        "Missing required full_name field",
                        "Invalid full_name field format: Starts with one or more letters, allows for characters like spaces, hyphens, apostrophes, commas, periods within the name, does not allow trailing spaces",
                        "Invalid email field format: The email address must contain at least one character before and after the '@' symbol and end with an extension like .com, .net, .org.",
                        "Invalid password field format: The length of the string must be between 7 and 50 characters.
                        It must contain at least one digit.
                        It must contain at least one uppercase letter ",
                        "Password and confirm password do not match",
                      ]
        "409":
          description: "Return this response if one of the following error occurs: 108"
          content:
            application/json:
              examples:
                error_108_example:
                  $ref: "#/components/examples/error_108_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
  /users:
    get:
      tags:
        - users
      operationId: get_users
      parameters:
        - $ref: "#/components/parameters/page_size_param"
        - $ref: "#/components/parameters/page_param"
      responses:
        "200":
          description: A paginated list of users
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/paginated_total"
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/user_info"
                required:
                  - data
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  value:
                    error_code: 104
                    message: Invalid syntax
                    details:
                      [
                        The invalid parameter is passed to the page. The 'page' parameter must be a number greater than 0,
                        The invalid parameter is passed to the page_size. The 'page_size' parameter must be a number greater than 0,
                      ]
        "401":
          description: "Return this response if one of the following error occurs: 116"
          content:
            application/json:
              examples:
                error_116_example:
                  $ref: "#/components/examples/error_116_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
    put:
      tags:
        - users
      operationId: update_user
      description: Users can edit their own information
      parameters:
        - in: body
          name: data
          required: true
          description: User information data to be updated
          schema:
            type: object
            properties:
              full_name:
                type: string
                example: Pham Tien
                description: |-
                  ^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$
                  (Starts with one or more letters,
                  allows for characters like spaces,
                  hyphens, apostrophes, commas,
                  and periods within the name,
                  and does not allow trailing spaces)
              email:
                type: string
                example: user@gmail.com
                description: |-
                  ^.*@.*\.(com|net|org)$
                  (The email address must contain at least one character before and after the '@' symbol,
                  and end with an extension like .com, .net, .org.)
            required:
              - full_name
              - email
      responses:
        "200":
          description: User information updated successfully.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_info"
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  value:
                    error_code: 104
                    message: Invalid syntax
                    details:
                      [
                        "Missing required email field",
                        "Missing required full_name field",
                        "Invalid full_name field format: Starts with one or more letters, allows for characters like spaces, hyphens, apostrophes, commas, periods within the name, does not allow trailing spaces",
                        "Invalid email field format: The email address must contain at least one character before and after the '@' symbol and end with an extension like .com, .net, .org.",
                      ]
        "401":
          description: "Return this response if one of the following error occurs: 116"
          content:
            application/json:
              examples:
                error_116_example:
                  $ref: "#/components/examples/error_116_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
  admin/users/{id}:
    delete:
      tags:
        - admin
      operationId: delete_user
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the user to delete information.
          schema:
            type: integer
            example: 123
      responses:
        "204":
          description: User information deleted successfully
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  value:
                    error_code: 104
                    message: Invalid syntax
                    details:
                      [
                        The provided user ID is in an invalid format. The ID must be a number greater than 0,
                      ]
        "401":
          description: "Return this response if one of the following error occurs: 116"
          content:
            application/json:
              examples:
                error_116_example:
                  $ref: "#/components/examples/error_116_example"
        "403":
          description: "Return this response if one of the following error occurs: 113"
          content:
            application/json:
              examples:
                error_113_example:
                  $ref: "#/components/examples/error_113_example"
        "404":
          description: "Return this response if one of the following error occurs: 112"
          content:
            application/json:
              examples:
                error_112_example:
                  $ref: "#/components/examples/error_112_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
    put:
      tags:
        - admin
      operationId: update_user
      description: The admin can edit user information
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the user to update information
          schema:
            type: integer
            example: 123
        - in: body
          name: data
          required: true
          description: User information data to be updated
          schema:
            type: object
            properties:
              full_name:
                type: string
                example: Pham Tien
                description: |-
                  ^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$
                  (Starts with one or more letters,
                  allows for characters like spaces,
                  hyphens, apostrophes, commas,
                  and periods within the name,
                  and does not allow trailing spaces)
              email:
                type: string
                example: user@gmail.com
                description: |-
                  ^.*@.*\.(com|net|org)$
                  (The email address must contain at least one character before and after the '@' symbol,
                  and end with an extension like .com, .net, .org.)
              role_id:
                type: integer
                example: 2
            required:
              - full_name
              - email
              - role_id
      responses:
        "200":
          description: User information updated successfully.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_info"
        "400":
          description: "Return this response if one of the following error occurs: 104, 115"
          content:
            application/json:
              examples:
                error_104_example:
                  value:
                    error_code: 104
                    message: Invalid syntax
                    details:
                      [
                        "Missing required email field",
                        "Missing required full_name field",
                        "Missing required role_id field",
                        "Invalid full_name field format: Starts with one or more letters, allows for characters like spaces, hyphens, apostrophes, commas, periods within the name, does not allow trailing spaces",
                        "Invalid email field format: The email address must contain at least one character before and after the '@' symbol and end with an extension like .com, .net, .org.",
                        "The provided user ID is in an invalid format. The ID must be a number greater than 0",
                      ]
                error_115_example:
                  $ref: "#/components/examples/error_115_example"
        "401":
          description: "Return this response if one of the following error occurs: 116"
          content:
            application/json:
              examples:
                error_116_example:
                  $ref: "#/components/examples/error_116_example"
        "403":
          description: "Return this response if one of the following error occurs: 114"
          content:
            application/json:
              examples:
                error_114_example:
                  $ref: "#/components/examples/error_114_example"
        "404":
          description: "Return this response if one of the following error occurs: 112"
          content:
            application/json:
              examples:
                error_112_example:
                  $ref: "#/components/examples/error_112_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
components:
  schemas:
    user_info:
      type: object
      properties:
        id:
          type: integer
          example: 123
        full_name:
          type: string
          example: Pham Tien
        email:
          type: string
          example: user@gmail.com
        role:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: member
          required:
            - id
            - name
      required:
        - id
        - full_name
        - email
        - role
    paginated_total:
      type: object
      properties:
        total:
          type: integer
          example: 10
      required:
        - total
  parameters:
    page_param:
      name: page
      in: query
      description: Page to be displayed
      schema:
        type: integer
        default: 1
        example: 4
        required: page_param
    page_size_param:
      name: page_size
      in: query
      description: Number of results per page
      schema:
        type: integer
        default: 10
        example: 1
        required: page_size_param
  examples:
    error_102_example:
      value:
        error_code: 102
        message: Incorrect email or password
    error_103_example:
      value:
        error_code: 103
        message: An unexpected error occurred on the server
    error_108_example:
      value:
        error_code: 108
        message: Email already exists
    error_112_example:
      value:
        error_code: 112
        message: The user ID does not exist
    error_113_example:
      value:
        error_code: 113
        message: The user is not authorized to delete information
    error_114_example:
      value:
        error_code: 114
        message: The admin is not authorized to edit information of other admins
    error_115_example:
      value:
        error_code: 115
        message: Role with the provided ID does not exist
    error_116_example:
      value:
        error_code: 116
        message: Users must log in to access this resource
